== Fonctionnal quarters

To start with the microservices architecture, it is necessary to define the functional quarters of the application, to initiate a first separation of the application into microservices. A functionnal quarter is define by a set of user stories.

=== User story vocabulary

The following table contains the vocabulary of PolyCode. He is used to describe the user stories in the next section.

Guest:: Someone who doesn't have a PolyCode account.

User:: Someone who has a PolyCode account.

Admin:: A privilegied user that can manage all the resources of PolyCode.

Module:: A coherent set of module and contents, organized in a tree structure. A module can be a challenge, a practice, a certification, a submodule, a test, etc.

Content:: A coherent set of components, organized in a tree structure. It's a branch of the tree that are the modules. A content can be an exercice, a lesson, a question, etc.

Component:: A coherent set of components, organized in a tree structure. It's a branch or a leave of another branch that are the contents or the components. A component can be an code editor, a quizz, a markdown, a mcq, a container, etc.

Test:: A type of module. He is made to evaluate users. It has a grade, which is the average of the grades of all contents of the test.

Assessment:: A section of PolyCode made to evaluate users, by passing tests.

Campaign:: The realization of an assessment in a set of users. 

Candidate:: Someone who is invited to participate to a campaign. Became an user if he accepts the invitation.

Assessment creator:: A user who can create an test or an assessment, then invite someone to participate to it, as a candidate.

Practice creator:: A user who can manage his modules.

Submitable:: A component that can be submitted by the user. It can be a code editor, a quizz, a mcq, etc.

Validator:: The excepted response to a submitable.

Submission:: A user answer to a submitable. It is verified by a set of validators.

Tag:: A keyword that can be associated to a content, a candidate, etc.

Item:: A purchasable object. It can be a hint, a validator, etc.

Purchase:: The action of buying an item.

Hint:: A type of item that gives a clue to the user to solve a component. It is bought with polypoints.

Polypoints:: A virtual money responsible of the gamification of PolyCode. It can be used to buy items, like hints. It also used to rank users. The polypoints are collected by the users by passing modules and contents.

Team:: A group of users. The team polypoints are the sum of the polypoints of all users of the team, and is used to rank the teams.

Captain:: A user who can manage his team.

=== User stories

The following table contains the most of the user stories of PolyCode. It is not exhaustive, but it contains the most important user stories.

[cols="1,2,2", options="header"]
|===
^.^| As                 ^.^| I want
                        ^.^| So that

^.^| Guest              ^.^| Create my account
                        ^.^| Connect to my account.

^.^| User               ^.^| Connect to my account with my email and my password
                        ^.^| Use the PolyCode features.

^.^| User               ^.^| Logout from my account
                        ^.^| Remove my session and go back as a guest.

^.^| User               ^.^| Reset my password
                        ^.^| Edit my credentials.

^.^| User               ^.^| Show my profile
                        ^.^| See my user information.

^.^| User               ^.^| Update my profile, emails or user settings.
                        ^.^| Edit my user information.

^.^| User               ^.^| Receive a welcome email when I sign up
                        ^.^| Know that my account is created.

^.^| User               ^.^| Show a user profile
                        ^.^| Get some information about a user (pseudo, rank, etc).

^.^| User               ^.^| Delete my account
                        ^.^| Delete my user information.

^.^| User               ^.^| Create a new team
                        ^.^| Become a captain of a team.

^.^| Captain            ^.^| Invite other users in my team
                        ^.^| Grow my team and make it more active.

^.^| Captain            ^.^| Kick a member from my team
                        ^.^| Remove a member who is not active anymore or who is not a good fit for the team.

^.^| Captain            ^.^| Give the captain role to another member of my team
                        ^.^| Promote a member who is more active than me.

^.^| Captain            ^.^| Delete my team
                        ^.^| Dissolve my team.

^.^| Captain            ^.^| Update my team details
                        ^.^| Edit my team information.

^.^| User               ^.^| Accept an invitation to join a team
                        ^.^| Join a team.

^.^| User               ^.^| Reject an invitation to join a team
                        ^.^| Don't join a team.

^.^| User               ^.^| Leave a team
                        ^.^| No longer be a member of a team.

^.^| User               ^.^| Show a team profile
                        ^.^| Get some information about a team (name, rank, etc).

^.^| User               ^.^| Show the ranking of the teams
                        ^.^| Compare my team with other teams.

^.^| User               ^.^| Show the ranking of the users
                        ^.^| Compare my rank with other users.

^.^| User               ^.^| Show content list
                        ^.^| Choose an content to do.

^.^| User               ^.^| Show module list
                        ^.^| Choose a module to do.

^.^| User               ^.^| Show the description of a module
                        ^.^| Take information about the module.

^.^| User               ^.^| Show test list
                        ^.^| Choose a test to do.

^.^| User               ^.^| Show new modules and contents
                        ^.^| Find modules that I never did.

^.^| User               ^.^| Show the description of a content
                        ^.^| Take information about the content.

^.^| User               ^.^| Show the description of a test
                        ^.^| Take information about the test.

^.^| User               ^.^| Submit a solution to a component
                        ^.^| Complete a content then earn polypoints.

^.^| User               ^.^| For a code editor, submit a solution for only one validator
                        ^.^| Check if my solution is correct for a specific validator.

^.^| User               ^.^| Show the last submissions of a component who passed all validators
                        ^.^| Improve my old solution.





^.^| User               ^.^| Écrire (et modifier) sa solution de code dans un éditeur intégré à la page de l'exercice (cas d'exercice de code)
                        ^.^| proposer une solution à l'exercice

^.^| User               ^.^| ajouter des fichiers dans l'éditeur (exercice)
                        ^.^| Organiser la solution en plusieurs fichiers

^.^| User               ^.^| supprimer des fichiers dans l'éditeur
                        ^.^| Organiser la solution en plusieurs fichiers

^.^| User               ^.^| acheter des données de validateur (entrée + sortie) avec des PolyPoints ⇒ hint
                        ^.^| comprendre mieux comment résoudre l'exercice

^.^| User               ^.^| suivre ma progression dans chacun des modules
                        ^.^| Voir ce qui est complété / à faire

^.^| User               ^.^| voir le classement global des utilisateurs (par polypoints)
                        ^.^| Motivation à atteindre le sommet (principe de concurrence)

^.^| User               ^.^| passer une évaluation
                        ^.^| obtenir une certification

^.^| User               ^.^| lire le contenu d'un cours
                        ^.^| monter en compétence sur un sujet

^.^| Content creator    ^.^| créer un exercice, et y ajouter du markdown, un code editor, un QCM organisé dans des conteneurs
                        ^.^| Proposer l'apprentissage d'une nouvelle notion, faire vérifier la connaissance de cette notion par une question/ un code à écrire

^.^| Content creator    ^.^| créer un module
                        ^.^| Organiser les exercices par notion majeure / thématique

^.^| Assessment creator ^.^| créer une évaluation
                        ^.^| vérifier les compétence d'un utilisateur sur un contenu

^.^| Content creator    ^.^| ajouter ses exercices à un module qu'il a créé
                        ^.^| remplir le contenu d'un module en ensemble d'élément cohérent

^.^| Content creator    ^.^| ajouter des modules dans un module, et ce avec des modules qu'il a créé (sous-module)
                        ^.^| remplir le contenu d'un module en ensemble d'élément cohérent

^.^| Content creator    ^.^| modifier le nom, la description, le nombre de PolyPoints de récompense, les tags, le contenu (exercices et sous-module) de ses modules
                        ^.^| Garder à jour un module

^.^| Content creator    ^.^| modifier le titre, la description, le contenu, récompense en polypoints,  les validateurs, les tags d'un exercice
                        ^.^| Garder à jour un exercice
                        
^.^| Content creator    ^.^| modifier le titre, la description, le contenu d'une évaluation
                        ^.^| Garder à jour une évaluation

^.^| Content creator    ^.^| supprimer un exercice qu'il a créé
                        ^.^| Réparer une erreur / ne plus vouloir la présence de ce contenu

^.^| Content creator    ^.^| supprimer un module qu'il a créé
                        ^.^| Réparer une erreur / ne plus vouloir la présence de ce contenu

^.^| Content creator    ^.^| supprimer une évaluation qu'il a créé
                        ^.^| Réparer une erreur / ne plus vouloir la présence de ce contenu

^.^| Content creator    ^.^| voir le résultat des utilisateurs sur une évaluation qu'il a créé
                        ^.^| Pour que le recruteur / professeur voie le résultat des élèves pour attribuer une note / recruter

^.^| Admin              ^.^| Promouvoir un utilisateur en rédacteur
                        ^.^| qu'un utilisateur ai les droits d'un “redacteur”

^.^| Admin              ^.^| Promouvoir un utilisateur en admin
                        ^.^| qu'un utilisateur ai les droits d'un “admin”

^.^| Admin              ^.^| Créer un utilisateur
                        ^.^| Utiliser l'application avec un autre compte

^.^| Admin              ^.^| Récupérer les données d'un utilisateur
                        ^.^| Voir les informations confidentielles d'un compte utilisateur

^.^| Admin              ^.^| Mettre à jour les données d'un utilisateur
                        ^.^| Mettre à jour les informations personnelles afin qu'elles soient cohérentes

^.^| Admin              ^.^| Supprimer un utilisateur
                        ^.^| Ne plus donner accès à la plateforme pour un compte utilisateur

^.^| Admin              ^.^| Créer un exercice
                        ^.^| Proposer l'apprentissage d'une nouvelle notion, faire vérifier la connaissance de cette notion par une question/ un code à écrire

^.^| Admin              ^.^| modifier le titre, la description, le contenu, récompense en polypoints,  les validateurs, les tags d'un exercice
                        ^.^| Garder à jour un exercice

^.^| Admin              ^.^| Créer un module
                        ^.^| Créer un module afin de regrouper des contenus

^.^| Admin              ^.^| Récupérer les données d'un module
                        ^.^| Voir les informations et les contenus associés à ce module

^.^| Admin              ^.^| Mettre à jour les données d'un module
                        ^.^| Garde le module à jour

^.^| Admin              ^.^| Supprimer un module
                        ^.^| Effacer les traces du module sur la plateforme

^.^| Admin              ^.^| Créer une évaluation
                        ^.^| vérifier les compétence d'un utilisateur sur un contenu

^.^| Admin              ^.^| Récupérer les données d'une évaluation
                        ^.^| Voir les différentes données en lien avec une évaluation

^.^| Admin              ^.^| Mettre à jour les données d'une évaluation
                        ^.^| Ajouter des utilisateurs ou modifier des données relatives à une évaluation

^.^| Admin              ^.^| Supprimer une évaluation
                        ^.^| Enlever une évaluation de la plateforme

^.^| Admin              ^.^| Créer une team
                        ^.^| Rassembler des utilisateurs dans une équipe

^.^| Admin              ^.^| Ajouter un membre dans mon équipe
                        ^.^| Proposer à un utilisateur de rejoindre mon équipe

^.^| Admin              ^.^| Supprimer un membre d'une team
                        ^.^| Enlever un utilisateur de mon équipe pour une quelconque raison

^.^| Admin              ^.^| Supprimer une team
                        ^.^| Supprimer une team qui ne valide pas les conditions d'utilisation

^.^| Admin              ^.^| Modifier la description d'une équipe
                        ^.^| Avoir une description à jour de l'équipe

^.^| Assessment creator ^.^| créer une campagne de test
                        ^.^| Evaluer le niveau des utilisateurs

^.^| Assessment creator ^.^| ajouter des utilisateurs à ma campagne via une interface web
                        ^.^| Faire participer les candidats

^.^| Assessment creator ^.^| supprimer des utilisateurs à ma campagne via une interface web
                        ^.^| Enlever un candidat des participants

^.^| Assessment creator ^.^| ajouter des utilisateurs à ma campagne via des appels API
                        ^.^| Faire participer les candidats

^.^| Assessment creator ^.^| supprimer des utilisateurs à ma campagne via des appels API
                        ^.^| Enlever un candidat des participants

^.^| Assessment creator ^.^| ajouter des utilisateurs à ma campagne via l'importation de fichiers csv
                        ^.^| Faire participer les candidats

^.^| Assessment creator ^.^| voir les résultats et statistiques sur la campagne que j'ai créé
                        ^.^| Me rendre compte du niveau des candidats testés

^.^| Assessment creator ^.^| ajouter des tags à mes candidats
                        ^.^| Grouper les candidats

^.^| Assessment creator ^.^| définir une date limite pour ma campagne
                        ^.^| Clôturer ma campagne à une date fixe

^.^| Candidate          ^.^| revenir sur un test et reprendre là où j'en était
                        ^.^| Finir mon test si jamais je quitte l'application

^.^| Assessment creator ^.^| définir un temps limite pour chaque question de ma campagne
                        ^.^| Les candidats répondent dans un temps limité

^.^| Assessment creator ^.^| définir un nb de points pour chaque question
                        ^.^| Avoir un score par candidats et voir leur différence de score à la fin de la campagne

^.^| Candidate          ^.^| recevoir un mail me permettant de participer à une campagne de tests
                        ^.^| Avoir un lien pour participer à une campagne

^.^| Candidate          ^.^| Accepter de participer à une campagne
                        ^.^| Tester ses compétences à travers une campagne

^.^| Candidate          ^.^| Refuser de participer à une campagne
                        ^.^| Avoir la possibilité de refuser une campagne et que le créateur en soit informé

^.^| Assessment creator ^.^| Éditer ma campagne, les tests liés
                        ^.^| Modifier une campagne précédemment créée

^.^| Assessment creator ^.^| Définir une date de début de ma campagne
                        ^.^| Définir une date pour les candidats, ainsi qu'un temps imparti pour finaliser la campagne

^.^| Assessment creator ^.^| Envoyer des liens de ma campagne manuellement à mes candidats
                        ^.^| S'assurer que les candidats reçoivent bien le lien pour participer à une campagne

^.^| Candidate          ^.^| Recevoir un mail de confirmation contenant des stats quand j'ai soumis mon test
                        ^.^| Notifier l'utilisateur que sa participation et ses réponses ont bien été enregistrées pour une campagne

^.^| Assessment creator ^.^| Voir le nombre de points totaux par candidats
                        ^.^| Comparer les points des candidats ayant participé à la campagne

^.^| Assessment creator ^.^| Visualiser un graphique/un excel par tags de content et par candidats
                        ^.^| Voir graphiquement les différents résultats
                        
^.^| Assessment creator ^.^| Exporter les résultats synthétisés dans un pdf
                        ^.^| Sauvegarder les résultats des candidats et avoir une vue synthétique

^.^| Assessment creator ^.^| Exporter les résultats détaillés dans un pdf
                        ^.^| Sauvegarder les résultats des candidats et y avoir accès sans passer par l'application

^.^| Assessment creator ^.^| Avoir une vue comparative des candidats sous la forme d'un tableau excel
                        ^.^| Comparer les score des candidats à travers un tableau

^.^| Assessment creator ^.^| Trier la liste des candidats par tags, résultats
                        ^.^| Comparer les résultats des candidats en fonction de données précises

^.^| Assessment creator ^.^| télécharger les scores des candidats
                        ^.^| afin de garder les stats en local

^.^| User               ^.^| recevoir un mail quand je suis invité dans une team
                        ^.^| Etre prévenu que je peux rejoindre une équipe

^.^| User               ^.^| recevoir un mail quand une équipe dans laquelle je suis es supprimée
                        ^.^| Etre averti que mon équipe à été supprimée

^.^| User               ^.^| recevoir un mail quand je suis radié d'une équipe
                        ^.^| Etre averti que j'ai été éjecté d'une équipe
|===

=== Functional quarters

=== PolyCode microservices architecture